config/routes.rb
Rails.application.routes.draw do
  root to: 'payment_records#index'

  with_options controller: :sessions do
    get :signin, action: :new
    post :signin, action: :create
    delete :signout, action: :destroy
    get :signout, action: :destroy
  end

  resources :payment_records, only: [:index, :create] do
    collection do
      post :pdf
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment_record.rb
class PaymentRecord < ApplicationRecord
  belongs_to :user

  validates :item_name, presence: true
  validates :price,
            presence: true,
            numericality: { only_integer: true, allow_blank: true }

  scope :sorted, -> { order(id: :asc) }

  def dollar_price
    price / 100.0
  end

  def dollar_price=(dollar)
    return if dollar.blank?
    self.price = (dollar.to_f * 100).to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :payment_records, dependent: :destroy do
    def total_dollar_price
      total_price = sum(:price)
      total_price / 100.0
    end
  end

  validates :name,
            presence: true,
            uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :current_user

  private

  def current_user
    return @current_user if @current_user.present?

    if session[:user_id].present?
      @current_user = User.find_by(id: session[:user_id])
    end

    @current_user
  end

  def authenticate_user!
    redirect_to signin_path if current_user.blank?
  end

  def signin(user)
    session[:user_id] = user.id
  end

  def signout
    session.delete(:user_id)
  end
end

app/controllers/payment_records_controller.rb
class PaymentRecordsController < ApplicationController
  def index
    @payment_records = current_user.payment_records.sorted
    @total_dollar_price = current_user.payment_records.total_dollar_price
  end

  def create
    @payment_record = current_user.payment_records.create(payment_record_params)
    @total_dollar_price = current_user.payment_records.total_dollar_price
  end

  private

  def payment_record_params
    params.require(:payment_record).permit(:item_name, :dollar_price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  end

  def create
    user = User.find_or_create_by(name: params[:user_name])

    signin(user)
    redirect_to root_path
  end

  def destroy
    signout
    redirect_to signin_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payment_records_helper.rb
module PaymentRecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniWebsite</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payment_records/_payment_record.html.erb
<li>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="record-detail">
        <span class="item_name"><%= payment_record.item_name %></span>
        <span class="price">$<%= "%.2f" % payment_record.dollar_price %></span>
      </div>
    </div>
  </div>
</li>

app/views/payment_records/create.js.erb
<% if @payment_record.errors.any? %>
  alert('<%=j @payment_record.errors.full_messages.join(',') %>');
<% else %>
  document.querySelector('ul.record-list').insertAdjacentHTML('beforeend', '<%=j render(@payment_record) %>');
  document.querySelector('.total .number').innerHTML = '<%= "%.2f" % @total_dollar_price %>';
<% end %>

app/views/payment_records/index.html.erb
<main class="payment_records-index">
  <div class="container text-center">
    <div class="inner-container col-sm-6 col-sm-offset-3">
      <div class="header-panel">
        <h1>Payment Records</h1>
        <div class="user-panel">
          <span class="user-name label label-default">
            <%= current_user.name %>
            <%= link_to '×', signout_path, method: :delete, class: 'signout-link', data: { remote: true } %>
          </span>
        </div>
      </div>

      <div class="record-panel">
        <ul class="record-list">
          <%= render @payment_records %>
        </ul>
        <div class="total-panel clearfix">
          <div class="total pull-right">
            Total: $<span class="number"><%= "%.2f" % @total_dollar_price %></span>
          </div>
        </div>
      </div>

      <div class="form-panel">
        <%= form_with scope: :payment_record, url: payment_records_path, class: 'inline-form' do |f| %>
          <%= f.text_field :item_name, placeholder: 'Item Name', class: 'form-control' %>
          <%= f.text_field :dollar_price, placeholder: 'Price', class: 'form-control' %>
          <%= f.submit 'Add', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</main>